# `nesting.py`

This script computes the **electronic nesting function** from *ab initio* band-structure data.
It evaluates Fermi-surface matching between momentum points and estimates the nesting strength by Gaussian-smoothed integration over interpolated eigenvalues.

---

### Description

The program reads **`EIGENVAL`** and **`DOSCAR`** files generated by VASP, determines the Fermi energy, interpolates the band energies across a fine mesh, and evaluates the nesting function
[\xi(\mathbf{q}) = \sum_{\mathbf{k}} f(E_\mathbf{k}) , f(E_{\mathbf{k}+\mathbf{q}}),]
restricted to states near the Fermi level.
Parallel execution with Python’s `multiprocessing` enables efficient computation on multicore systems.

**Main features**

* Interpolation of eigenvalues using `CloughTocher2DInterpolator`
* Gaussian broadening in both k- and q-space
* Symmetry expansion of Fermi-surface points to cover the full Brillouin zone
* Parallel evaluation of the nesting function on a uniform q-mesh
* Output files:

  * `fromfs.dat`, `tofs.dat` — symmetry-expanded Fermi-surface points
  * `nesting_func.dat` — evaluated nesting function values
  * `interp_bnd.dat` — interpolated band energy map

---

### Usage

```bash
python nesting.py <sigma_q>
```

where `<sigma_q>` is the Gaussian width in reciprocal-space units (e.g., 0.05).
The script expects VASP-format `EIGENVAL` and `DOSCAR` files in the working directory.

Typical workflow:

1. Run a self-consistent VASP calculation to generate `EIGENVAL` and `DOSCAR`.
2. Execute `python nesting.py 0.05`.
3. Visualize `nesting_func.dat` with `gnuplot`, `matplotlib`, or another plotting tool.

---

### Citation

If you use or adapt this script, please cite:

> **X. Wang**, *Electronic Nesting Function and Fermi Surface Mapping in Transition-Metal Systems*,
> *Nano Letters* **2025**, DOI: [10.1021/acs.nanolett.5c04166](https://pubs.acs.org/doi/abs/10.1021/acs.nanolett.5c04166).
